name: Flutter_Web_On_Demand

on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Flutter version'
        required: true
        default: '2.5.3'

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set Flutter version
        uses: subosito/flutter-action@v2.2.0
        with:
          flutter-version: '${{ github.event.inputs.flutter_version }}'

      - name: Display Flutter version
        run: flutter --version
